[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
polygon_amoy = "https://rpc-amoy.polygon.technology"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
